snapshot_preserve_min   2d
snapshot_preserve       7d
snapshot_preserve       14d  # weekly
snapshot_preserve       4w   # monthly

volume /mnt/btrfs
  target /mnt/backup/rpi5
  subvolume @
    snapshot_name root
  subvolume @home
    snapshot_name home
  subvolume @var_log
    snapshot_name varlog
