[options]
Architecture = aarch64
SigLevel = Never
XferCommand = /usr/bin/aria2c --allow-overwrite=true --continue=true --file-allocation=none --log-level=error --max-tries=10 --max-connection-per-server=2 --max-file-not-found=5 --min-split-size=5M --no-conf --remote-time=true --summary-interval=60 --timeout=30 --retry-wait=10 --dir=/ --out %o %u

[core]
Server = http://de.mirror.archlinuxarm.org/$arch/$repo
Server = http://nl.mirror.archlinuxarm.org/$arch/$repo
Server = http://sg.mirror.archlinuxarm.org/$arch/$repo
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo
[extra]
Server = http://de.mirror.archlinuxarm.org/$arch/$repo
Server = http://nl.mirror.archlinuxarm.org/$arch/$repo
Server = http://sg.mirror.archlinuxarm.org/$arch/$repo
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo
[community]
Server = http://de.mirror.archlinuxarm.org/$arch/$repo
Server = http://nl.mirror.archlinuxarm.org/$arch/$repo
Server = http://sg.mirror.archlinuxarm.org/$arch/$repo
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo
[alarm]
Server = http://de.mirror.archlinuxarm.org/$arch/$repo
Server = http://nl.mirror.archlinuxarm.org/$arch/$repo
Server = http://sg.mirror.archlinuxarm.org/$arch/$repo
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo
[aur]
Server = http://de.mirror.archlinuxarm.org/$arch/$repo
Server = http://nl.mirror.archlinuxarm.org/$arch/$repo
Server = http://sg.mirror.archlinuxarm.org/$arch/$repo
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo
