#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
readonly PROJECT_ROOT
SRC_DIR="$PROJECT_ROOT/src"
readonly SRC_DIR
DIST_DIR="$PROJECT_ROOT/dist"
readonly DIST_DIR
DIST_BIN_DIR="$DIST_DIR/bin"
readonly DIST_BIN_DIR
DIST_IMAGES_DIR="$DIST_DIR/images"
readonly DIST_IMAGES_DIR
DIST_FILE="$DIST_BIN_DIR/rpi5-archlinux-image"
readonly DIST_FILE
BUILD_CONFIG_FILE="$PROJECT_ROOT/build.conf"
readonly BUILD_CONFIG_FILE

if [[ ! -f "$BUILD_CONFIG_FILE" ]]; then
    printf 'ERROR: build.conf is required. Create it with: cp build.conf.example build.conf\n' >&2
    exit 1
fi

append_without_header() {
    local path="$1"

    # shellcheck disable=SC2016
    sed \
        -e '1{/^#!\/bin\/bash$/d;}' \
        -e '/^# shellcheck disable=SC109[01]$/d' \
        -e '/^source "\$BUILD_LIB_DIR\/.*"$/d' \
        -e '/^source "\$BUILD_CORE_DIR\/.*"$/d' \
        -e '/^source "\$(dirname "\${BASH_SOURCE\[0\]}")\/log\.sh"$/d' \
        -e '/^source "\$MODULE_DISK_DIR\/colors\.sh"$/d' \
        "$path"
}

append_section() {
    local path="$1"

    {
        printf '\n# ---- %s ----\n' "${path#"$PROJECT_ROOT"/}"
        append_without_header "$path"
    } >>"$DIST_FILE"
}

mkdir -p "$DIST_BIN_DIR" "$DIST_IMAGES_DIR"

{
    printf '#!/bin/bash\n'
    printf '# shellcheck disable=SC2034\n'
    printf '# Generated by scripts/package.sh. Edit src/ files instead.\n'
} >"$DIST_FILE"

append_section "$SRC_DIR/lib/colors.sh"
append_section "$SRC_DIR/lib/log.sh"
append_section "$SRC_DIR/lib/disk.sh"
append_section "$SRC_DIR/lib/bootstrap.sh"
append_section "$SRC_DIR/lib/qemu.sh"
append_section "$SRC_DIR/lib/core/config.sh"
append_section "$SRC_DIR/lib/core/deps.sh"
append_section "$SRC_DIR/lib/core/assets.sh"
append_section "$SRC_DIR/lib/core/steps.sh"
append_section "$SRC_DIR/lib/core/modules.sh"
append_section "$SRC_DIR/lib/core/runner.sh"

{
    printf '\n# ---- embedded default build config ----\n'
    printf 'config::load_embedded_default() {\n'
    cat "$BUILD_CONFIG_FILE"
    printf '\n}\n'
} >>"$DIST_FILE"

for module_path in "$SRC_DIR"/lib/modules/*.sh; do
    append_section "$module_path"
done

{
    printf '\n# ---- embedded src/conf assets ----\n'
    printf 'assets::write_embedded() {\n'
    # shellcheck disable=SC2016
    printf '    local asset_path="$1"\n'
    # shellcheck disable=SC2016
    printf '    local target_path="$2"\n'
    printf '\n'
    # shellcheck disable=SC2016
    printf '    case "$asset_path" in\n'
} >>"$DIST_FILE"

while IFS= read -r asset_source; do
    asset_path="${asset_source#"$SRC_DIR/conf"/}"
    {
        printf '        %q)\n' "$asset_path"
        printf "            cat <<'RPI5_ASSET_EOF' >\"\$target_path\"\n"
        cat "$asset_source"
        printf '\nRPI5_ASSET_EOF\n'
        printf '            ;;\n'
    } >>"$DIST_FILE"
done < <(find "$SRC_DIR/conf" -type f | sort)

{
    printf '        *)\n'
    printf '            return 1\n'
    printf '            ;;\n'
    printf '    esac\n'
    printf '}\n'
} >>"$DIST_FILE"

append_section "$SRC_DIR/main.sh"
chmod +x "$DIST_FILE"

printf 'Built %s\n' "${DIST_FILE#"$PROJECT_ROOT"/}"
